### PR TITLE
[DC-2469] Upgrade qgrid from 1.2.1 to 1.3.1 for compatability issues

### PR DESCRIPTION
**Pull request by nishanthpp93**
* [DC-2469] Update requirements.txt

[DC-2469]: https://precisionmedicineinitiative.atlassian.net/browse/DC-2469?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by ksdkalluri — COMMENTED** [review]
@nishanthpp93 are the other changes dependencies for qgrid?

**Comment by nishanthpp93** [comment]
I think these were missed from previous dependencies.

**Comment by nishanthpp93** [comment]
@ksdkalluri Let me know if you see different packages in your venv

**Review by ksdkalluri — APPROVED** [review]
I just installed `qgrid==1.3.1` and ran pip freeze, it has all these changes. This should be good to merge.

**Pull request merged**
