### PR TITLE
Set datetime fields to nullable rather than required

### PR DESCRIPTION
**Pull request by mark-velez**
* As defined by OMOP spec (see https://github.com/OHDSI/CommonDataModel)
 * Datetimes in observation_period will likely be removed (see https://github.com/OHDSI/CommonDataModel/pull/64)

### CODE REVIEW

**Comment by mark-velez** [comment]
Were `tools/bq/schemas/*.json` auto-genned from a DDL in https://github.com/OHDSI/CommonDataModel? If so, where from (so I might report bug)?

**Comment by danqrodney** [comment]
Yeah, they were generated from e.g.  https://github.com/OHDSI/CommonDataModel/blob/master/PostgreSQL/OMOP%20CDM%20ddl%20-%20PostgreSQL.sql#L347

where start timestamps are not nullable.

If that's wrong, it seems to be wrong with the DDL, too.

What's the point of adding these columns but allowing them to be null when the date version isn't? (Shouldn't they always have the date value's timestamp in there?)

**Comment by danqrodney** [comment]
(I do understand allowing them to be nullable at least temporarily when upgrading an existing database, but it seems like for analysis purposes you'd want all the non-nullable date fields to have corresponding non-nullable datetime fields.)

**Comment by mark-velez** [comment]
No longer relevant

**Pull request closed without merging**
