### PR TITLE
[DC-3058] Deprecate bq.py and bq_utils.py helper functions with a warning

### PR DESCRIPTION
**Pull request by lledezma**

### CODE REVIEW

**Review by nishanthpp93 — APPROVED** [review]
Looks good! I would also prefer something like `use xyz instead`, but this is also fine.

**Comment by lledezma** [comment]
I thought about doing what you suggested, but I couldn't find suitable replacements within project.

**Comment by nishanthpp93** [comment]
> I thought about doing what you suggested, but I couldn't find suitable replacements within project.

Aren't these moved to common? You can just say use the constants in common.py. For the other functions, are they not replaced by something else?

**Comment by lledezma** [comment]
They were not moved to common and replacements were not created because they are not used at all in curation.

**Pull request merged**
