### PR TITLE
New Data Quality Metrics

### PR DESCRIPTION
**Pull request by noahgengel**
Updates include:

- Changes to the metrics_over_time script (more versatility and metrics)
- Visualizations for Cleaning Rules #389 and #272 
- Comparing AoU data to the Data Quality Dashboard Visualizations
- Mapping out 'foreign key' date discrepancies
- Looking at information on notes (sites, titles, etc.)
- Improved docstrings
- Identifying outliers in the measurement table for particular sites

### CODE REVIEW

**Comment by noahgengel** [comment]
let me know if you would want me to create a new branch then squash some of the above commits together. i recognize 23 commits may be overwhelming.

**Comment by noahgengel** [comment]
NOTE: I have a couple other files in my personal repo that should be pushed to the all-of-us develop branch. 

I will, however, wait until this branch is merged to open another pull request (in an attempt to prevent my PR from re-introducing a large number of commits).

**Comment by nishanthpp93** [comment]
Hey @noahgengel, the history on this is not linear and there are a lot of entanglements happening. You will have to cherry pick your commits onto a new branch to fix this. Let me know when you're free and we can go over it.

**Comment by nishanthpp93** [comment]
Duplicated in https://github.com/all-of-us/curation/pull/402

**Pull request closed without merging**
