### PR TITLE
[DC-2314] [RT] add standard and replacement suppressed concept_ids

### PR DESCRIPTION
**Pull request by brendagutman**

### CODE REVIEW

**Review by lrwb-aou — COMMENTED** [review]
These map to 37 codes.  ✅ 
I did notice that 13 appear to be deprecated.  Did you expect this?  It won't hurt to leave them in, I just want to make sure this is expected.

**Comment by brendagutman** [comment]
Those are most likely the concepts that replaced something, and then were replaced themselves. I can check on those if you want.

**Comment by lrwb-aou** [comment]
Please confirm that.

**Comment by brendagutman** [comment]
These are concepts that are equivalent to a suppressed concept. They are invalid and not standards.

**Comment by lrwb-aou** [comment]
@brendagutman one other question, why are there only 37 added concepts?  I expected more.

**Comment by brendagutman** [comment]
I checked the concepts I had listed against the file for duplicates. I hadn't done that previously.

**Review by lrwb-aou — APPROVED** [review]
This looks good!

**Pull request merged**
