### PR TITLE
[DC-2609] Update the survey_version_info with new year minute

### PR DESCRIPTION
**Pull request by brendagutman**

### CODE REVIEW

**Review by molly-giddings — CHANGES_REQUESTED** [review]
@brendagutman - The code update looks good!  Could you update two minor things:

- Add DC-2609 to the list of ISSUE_NUMBERS on line 27
- Update the comment at the top of the file to reflect that it is both COPE and minute surveys

**Comment by brendagutman** [comment]
Sure thing Molly, the changes have been made. I updated a few of the other descriptor lines as well to account for the Minute surveys.

**Comment by molly-giddings** [comment]
Thanks,  @brendagutman !  I think it's failing for a missing apostrophe on line 27, but otherwise looks good.

**Comment by brendagutman** [comment]
New branch for changes bg/dc_2609_a. Closing PR

**Pull request closed without merging**
