### PR TITLE
[DC-1733] Simplify and fix query in temp_consistency

### PR DESCRIPTION
**Pull request by nishanthpp93**
* [DC-1733] Remove left joins

[DC-1733]: https://precisionmedicineinitiative.atlassian.net/browse/DC-1733

### CODE REVIEW

**Review by lrwb-aou — COMMENTED** [review]
Consider adding the following test patch changes.  It should fail on the current develop branch, but pass here.  Just to exercise this patch and make sure we include a test case that exercises this scenario.

[temporal_consistency_test_patch.txt](https://github.com/all-of-us/curation/files/6719068/temporal_consistency_test_patch.txt)

**Comment by ksdkalluri** [comment]
@nishanthpp93 can you update DC-1731 to reflect these changes in the scope and make link this PR.

**Comment by nishanthpp93** [comment]
@ksdkalluri I think it's better to not change the scope and keep them separate. DC-1731 should be the investigation ticket and DC-1733 the fix. I've linked the tickets so they can be referenced easily.

**Comment by nishanthpp93** [comment]
@lrwb-aou Thank you for updating the test to verify! I have applied the patch and it passes successfully.

**Review by lrwb-aou — APPROVED** [review]
The `TemporalConsistencyTest` has passed now.  It all looks good to merge!

**Pull request merged**
