### PR TITLE
[DC-1893] Invalid Zip Code concept code applied to wrong field

### PR DESCRIPTION
**Pull request by jp3477**
Changed set field values of invalid zip code concepts.

### CODE REVIEW

**Review by ratuagga — DISMISSED** [review]
For the listing error, just adding an empty commit with commit message starting with '[DC-1893]' should fix it.

**Comment by lrwb-aou** [comment]
@jp3477 I think @ratuagga is correct, you would need to either add or amend your commit message to get past the linting check.  I ran the cleaning rule on some mocked data and it performs as expected.  I did notice that the integration tests didn't actually run, so I kicked them off.  I don't expect any issues, but will wait until they complete.

**Comment by jp3477** [comment]
@ratuagga and @lrwb-aou Thanks for the suggestion, I added the new commit. The tests are running again.

**Review by lrwb-aou — APPROVED** [review]
Coverage results indicate the tests were run.  This will be good to merge once all tests finish.

**Pull request merged**
