### PR TITLE
[DC-2272] ethnicity_source_concept_id and ethnicity_source_value are not broken down in registered tier

### PR DESCRIPTION
**Pull request by jp3477**

### CODE REVIEW

**Review by lrwb-aou — CHANGES_REQUESTED** [review]
This isn't working.  I got the same failure when I ran the integration test locally.

**Comment by jp3477** [comment]
Hi @lrwb-aou, they're failing locally for me as well. Looked at it earlier today, but haven't figured it out yet. Will try again tomorrow.

**Comment by lrwb-aou** [comment]
No problem.  Just didn't want you to be waiting on my review.

**Comment by jp3477** [comment]
@lrwb-aou Thanks for taking a look. Looks like I was missing a concept insert in the integration test. Hopefully it passes now.

**Comment by jp3477** [comment]
> @lrwb-aou Thanks for taking a look. Looks like I was missing a concept insert in the integration test. Hopefully it passes now.

Just noticed the `copy_vocab_tables` method that you recently created. Very convenient, could have maybe avoided this issue.

**Review by lrwb-aou — COMMENTED** [review]
I wanted to make sure it could handle someone selecting a race and an ethnicity concept, so I experimented with adding a test case.  Look at the patch and let me know what you think
[repopulate_person_post_deid_test_patch.txt](https://github.com/all-of-us/curation/files/9284172/repopulate_person_post_deid_test_patch.txt)
.

**Comment by jp3477** [comment]
> I wanted to make sure it could handle someone selecting a race and an ethnicity concept, so I experimented with adding a test case. Look at the patch and let me know what you think [repopulate_person_post_deid_test_patch.txt](https://github.com/all-of-us/curation/files/9284172/repopulate_person_post_deid_test_patch.txt) .

I think it looks great, much cleaner. You can commit your patch or I can if your prefer.

**Comment by lrwb-aou** [comment]
> > I wanted to make sure it could handle someone selecting a race and an ethnicity concept, so I experimented with adding a test case. Look at the patch and let me know what you think [repopulate_person_post_deid_test_patch.txt](https://github.com/all-of-us/curation/files/9284172/repopulate_person_post_deid_test_patch.txt) .
> 
> I think it looks great, much cleaner. You can commit your patch or I can if your prefer.

Your PR. If you would like to commit it, you should.

**Comment by jp3477** [comment]
Sounds good, just added it

**Review by lrwb-aou — APPROVED** [review]
Looks good!

**Pull request merged**
