### PR TITLE
[DC-1297] Update get_client() in utils/bq.py

### PR DESCRIPTION
**Pull request by nishanthpp93**
[DC-1297] Update bq.get_client() to require project and accept creds

[DC-1297]: https://precisionmedicineinitiative.atlassian.net/browse/DC-1297

### CODE REVIEW

**Comment by amcgrenera-vumc** [comment]
This all looks good to me, I double checked to make sure there are no usages of `get_client()` that do not currently pass `project_id` and I think we are good. I would also maybe add in a test to make sure it breaks if the `project` parameter is not given. The test I used to double check is below, if you want to add in!

``` 
# Tests if no project_id is given
self.assertRaises(TypeError, bq.get_client, project=None) 
```

**Comment by nishanthpp93** [comment]
Thanks for the suggestion, @amcgrenera-vumc! I've added the test.

**Review by amcgrenera-vumc — APPROVED** [review]
Thanks Nishanth! This looks good to me!

**Comment by nishanthpp93** [comment]
Thanks Aimee, I had forgotten to update the docstring so added that change!

**Pull request merged**
