### PR TITLE
[DC-2470] Add save figure ability to ad hoc notebooks

### PR DESCRIPTION
**Pull request by jp3477**

### CODE REVIEW

**Review by nishanthpp93 — CHANGES_REQUESTED** [review]
Looks good! Only change is to the commit message which has a different ticket number.

**Comment by jp3477** [comment]
@nishanthpp93 I had to rebase to fix failing integration tests, but should be good to go now.

**Comment by nishanthpp93** [comment]
Nice, looks good! Thanks @jp3477. When you merge, make sure to replace the PR title to be the same as the ticket name.

**Comment by jp3477** [comment]
Is it not the same now?

**Comment by nishanthpp93** [comment]
Yeah, but it'll swap it with the commit message instead during the merge.

**Review by nishanthpp93 — APPROVED** [review]

**Pull request merged**
