### PR TITLE
[DC-2630] Update truncate_rdr_using_date cleaning rule to include the survey_conduct table

### PR DESCRIPTION
**Pull request by nishanthpp93**
* [DC-2630] Update truncate_rdr_using_date for survey conduct

[DC-2630]: https://precisionmedicineinitiative.atlassian.net/browse/DC-2630?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by ksdkalluri — CHANGES_REQUESTED** [review]
@nishanthpp93 I would say add this ticket number to ISSUE_NUMBERS.

**Review by ksdkalluri — APPROVED** [review]
looks good!

**Review by molly-giddings — COMMENTED** [review]
Thank you, @nishanthpp93 !

**Comment by nishanthpp93** [comment]
I didn't realize that you were the reviewer @molly-giddings, I'll wait next time before merging!

**Pull request merged**
