### PR TITLE
[DC-2583] Add api_project_id as parameter to clean_digital_health_data.py

### PR DESCRIPTION
**Pull request by jp3477**

### CODE REVIEW

**Review by hiro-mishima — APPROVED** [review]
Looks good!

**Comment by jp3477** [comment]
> Looks good!
> 
> The integration test has not run with CircleCi for this PR yet. I tried to run it, but I got that the bucket names too long error. Could you please run the test before merging just in case? Thanks!

Hmm, strange errors are popping up in the integration tests. Looking into them.

**Comment by nishanthpp93** [comment]
I ran into this too, Google Cloud networking is having issues according to [status.g](http://status.cloud.google.com):
image

**Comment by jp3477** [comment]
Thanks for finding this, I'll try again later then.

**Pull request merged**
