### PR TITLE
[DC-879] Clean extension table mapping rule uses incorrect description

### PR DESCRIPTION
**Pull request by dcampbell-vumc**
Updated description in `clean_mapping.py`

### CODE REVIEW

**Comment by dcampbell-vumc** [comment]
@nishanthpp93 Unsure why all the circle tests are failing. I only changed the description in `clean_mapping.py`

**Comment by nishanthpp93** [comment]
Yeah that's odd. Does re-running the workflow help?

**Comment by dcampbell-vumc** [comment]
Yes. Lauren believes this error is stemming from an issue with the environment. Nothing is passing but integration tests before PR's are submitted. The last passing test was [2743](https://circleci.com/gh/all-of-us/curation/2743)

**Comment by dcampbell-vumc** [comment]
@nishanthpp93 All checks have passed, is this good to merge?

**Pull request merged**
