### PR TITLE
Added hpo_id for the UC consortium

### PR DESCRIPTION
**Pull request by cukarthik**

### CODE REVIEW

**Comment by danqrodney** [comment]
I noticed this PR, and thought I'd mention: RDR maintains a list of awardees, orgs, and sites here:

https://github.com/all-of-us/raw-data-repository/tree/master/rest-api/data

I don't think it's using the same IDs you're using here; and I'm not sure if it would make sense to change that in future. Just figured I should bring it up.

**Comment by cukarthik** [comment]
thanks @danqrodney! we weren't sure the rdr had it at the site level, but it looks like [this file](https://github.com/all-of-us/raw-data-repository/blob/master/rest-api/data/organizations.csv) is what we want to use. we'll work on using this list of codes to stay consistent.

**Comment by mark-velez** [comment]
@cukarthik do you want to continue with this pr for now and handle using the rdr file in a subsequent pr?

**Comment by cukarthik** [comment]
Yes. Making the change of the codes will require more testing.

**Comment by mark-velez** [comment]
This has been merged. Since it is a hotfix, I cherry-picked the relevant commits and merged it to `master`.

**Pull request closed without merging**
